Un serveur n'as pas plus etre créé:
-->Le problème provient surement d'une erreur dans le fichier XML des serveur


Traceback (most recent call last):
  File "/home/hannibal/Documents/projet&&truc_a_rendre/TeXloud/Frontales/FrontalCompilation/src/Main.py", line 33, in <module>
    o=Ordonnanceur.Ordonnanceur("./../fichierServeur.xml", "compilation")
  File "/home/hannibal/Documents/projet&&truc_a_rendre/TeXloud/Frontales/FrontalCompilation/src/Ordonnanceur.py", line 71, in __init__
    raise Exception
Exception
